src/api/home/content-types/home/schema.json, src/components/home/hero-carousel.json, src/components/home/home-carousel.json, types/generated/components.d.ts, types/generated/contentTypes.d.ts
=> Hero carousel

src/api/header/content-types/header/schema.json, src/api/header/controllers/header.ts, src/api/header/routes/header.ts, src/api/header/services/header.ts, src/components/menu/dropdown.json, src/components/menu/link.json, types/generated/components.d.ts, types/generated/contentTypes.d.ts
=> Header created

.github/workflows/dev-deploy.yml, src/components/home/description.json, src/components/home/grab-deals.json, src/components/home/harbour-air-article.json, src/components/home/hero-carousel.json, src/components/home/home-instagram.json, src/components/home/home-stay-update.json, types/generated/components.d.ts
* instagram-footer section added
* Name Changes done
* Name and Order changed
=> Name and section order changed (#19)

src/api/location/content-types/location/schema.json, src/api/location/controllers/location.ts, src/api/location/routes/location.ts, src/api/location/services/location.ts, src/api/main-location/content-types/main-location/schema.json, src/api/main-location/controllers/main-location.ts, src/api/main-location/routes/main-location.ts, src/api/main-location/services/main-location.ts, src/components/inside-location/additional-information.json, src/components/inside-location/additionalinfo-details.json, src/components/inside-location/direction.json, src/components/inside-location/starting-point.json, src/components/main-location/locations.json, types/generated/components.d.ts, types/generated/contentTypes.d.ts, yarn.lock
=> Inside location

src/api/career-opportunity/content-types/career-opportunity/schema.json, src/api/country/content-types/country/schema.json, src/api/deal/content-types/deal/schema.json, src/components/careers/careers-table.json, src/components/common/accordian.json, types/generated/components.d.ts, types/generated/contentTypes.d.ts
=> Deals collection updated

src/api/career-opportunity/content-types/career-opportunity/schema.json, src/api/country/content-types/country/schema.json, src/api/deal/content-types/deal/schema.json, types/generated/contentTypes.d.ts
=> Country collection additional fields added

src/api/tour-location/content-types/tour-location/schema.json, types/generated/contentTypes.d.ts
Added booking widget on clicking book button
=> tour booking

src/api/air-craft-fleet/content-types/air-craft-fleet/schema.json, src/api/air-craft-fleet/controllers/air-craft-fleet.ts, src/api/air-craft-fleet/routes/air-craft-fleet.ts, src/api/air-craft-fleet/services/air-craft-fleet.ts, src/components/aircraft-fleet/aircraft-fleet-tabs.json, src/components/aircraft-fleet/fleet-info.json, src/components/elements/pricing-table.json, src/components/elements/title-with-description.json, types/generated/components.d.ts, types/generated/contentTypes.d.ts
=> #73 Aircraft Fleet

src/components/elements/title-with-image.json, types/generated/components.d.ts
=> #76 Title With Image Component Update

src/api/luggage/content-types/luggage/schema.json, src/api/luggage/controllers/luggage.ts, src/api/luggage/routes/luggage.ts, src/api/luggage/services/luggage.ts, src/components/luggage/hero-description.json, src/components/luggage/luggage-allowance-table.json, src/components/luggage/luggage-allowance.json, src/components/luggage/luggage-dimensions-table.json, src/components/luggage/special.json, src/components/luggage/travelling-with-excess-luggage.json, types/generated/components.d.ts, types/generated/contentTypes.d.ts
=> #71: Luggage page created

src/api/assistance/content-types/assistance/schema.json, src/api/document/content-types/document/schema.json, src/api/document/controllers/document.ts, src/api/document/routes/document.ts, src/api/document/services/document.ts, src/components/elements/accordion-with-ck-editor.json, src/components/extra-assistance/accordion-with-editor.json, src/components/extra-assistance/files.json, types/generated/components.d.ts, types/generated/contentTypes.d.ts
=> #80: Extra assistance

src/api/parcel-express/content-types/parcel-express/schema.json, src/api/parcel-express/controllers/parcel-express.ts, src/api/parcel-express/routes/parcel-express.ts, src/api/parcel-express/services/parcel-express.ts, src/components/elements/title-with-ck-editor.json, src/components/parcel-express/faq.json, src/components/parcel-express/how-to-accordion.json, src/components/parcel-express/rates.json, src/components/parcel-express/shipping-cost.json, types/generated/components.d.ts, types/generated/contentTypes.d.ts
=> Parcel Express

src/api/air-craft-fleet/content-types/air-craft-fleet/schema.json, src/api/blog/content-types/blog/schema.json, src/api/blog/controllers/blog.ts, src/api/blog/routes/blog.ts, src/api/blog/services/blog.ts, src/api/blogs-and-new/content-types/blogs-and-new/schema.json, src/api/blogs-and-new/controllers/blogs-and-new.ts, src/api/blogs-and-new/routes/blogs-and-new.ts, src/api/blogs-and-new/services/blogs-and-new.ts, src/api/category/content-types/category/schema.json, src/api/category/controllers/category.ts, src/api/category/routes/category.ts, src/api/category/services/category.ts, src/api/news/content-types/news/schema.json, src/api/news/controllers/news.ts, src/api/news/routes/news.ts, src/api/news/services/news.ts, src/components/elements/instagram-images.json, types/generated/components.d.ts, types/generated/contentTypes.d.ts
=> HA-99: Blogs and News Content Type

src/api/destination/content-types/destination/schema.json, src/api/flight-status/content-types/flight-status/schema.json, src/api/flight-status/controllers/flight-status.ts, src/api/flight-status/routes/flight-status.ts, src/api/flight-status/services/flight-status.ts, types/generated/contentTypes.d.ts
=> Flight Status content type added

src/api/blog/content-types/blog/schema.json, src/api/blogs-and-new/content-types/blogs-and-new/schema.json, src/api/category/content-types/category/schema.json, src/api/news/content-types/news/schema.json, src/components/parcel-express/rates.json, types/generated/components.d.ts, types/generated/contentTypes.d.ts
=> HA-99 & HA-88 : Additional fields

src/api/home/content-types/home/schema.json, src/components/home/article-carousel.json, src/components/home/description.json, src/components/home/home-locations.json, src/components/home/home-tours.json, src/components/home/news.json, types/generated/components.d.ts, types/generated/contentTypes.d.ts
=> HA-174: Home Page content type updated

src/api/car-service/content-types/car-service/schema.json, types/generated/contentTypes.d.ts
Reverts tmuller-ha/harbour-air-backend-#180
=> Revert "Change in Car Services page content type"

src/api/book-flight/content-types/book-flight/schema.json, types/generated/contentTypes.d.ts
=> HA-366 : Book Flight Changes

config/plugins.ts, src/api/email-form/content-types/email-form/schema.json, src/api/email-form/controllers/email-form.ts, src/api/email-form/controllers/email-templates/baggage-claim-form.ts, src/api/email-form/controllers/email-templates/carservice-form.ts, src/api/email-form/controllers/email-templates/chartered-flight-request.ts, src/api/email-form/controllers/email-templates/contact-form.ts, src/api/email-form/controllers/email-templates/discounted-travel.ts, src/api/email-form/controllers/email-templates/group-bookings-form.ts, src/api/email-form/controllers/email-templates/high-flyer-rewards-application-form.ts, src/api/email-form/controllers/email-templates/index.ts, src/api/email-form/controllers/email-templates/inquiries-form.ts, src/api/email-form/controllers/email-templates/on-account-ticket.ts, src/api/email-form/controllers/email-templates/parcel-express-quote.ts, src/api/email-form/controllers/email-templates/tour-request.ts, src/api/email-form/controllers/email-templates/turbobucks-order-form.ts, src/api/email-form/controllers/formType.ts, src/api/email-form/routes/email-form.ts, src/api/email-form/services/email-form.ts, src/components/form/contact-form.json, src/components/form/users.json, types/generated/components.d.ts, types/generated/contentTypes.d.ts
=> HA-188: Forms Email api added

src/api/about-us/content-types/about-us/schema.json, src/api/award/content-types/award/schema.json, src/api/blog-list/content-types/blog-list/schema.json, src/api/community-involvement/content-types/community-involvement/schema.json, src/api/courtesy-shuttle/content-types/courtesy-shuttle/schema.json, src/api/luggage/content-types/luggage/schema.json, src/api/mobility/content-types/mobility/schema.json, src/api/news-list/content-types/news-list/schema.json, src/api/our-promise/content-types/our-promise/schema.json, src/api/parcel-express/content-types/parcel-express/schema.json, src/api/safety-first/content-types/safety-first/schema.json, src/components/seo/seo.json, types/generated/components.d.ts, types/generated/contentTypes.d.ts
This reverts commit d85e98d52f40370b3860736c02655dbae14a54ce.
=> Revert "Added SEO component for pages (#198)"

config/plugins.ts, types/generated/components.d.ts
Reverts tmuller-ha/harbour-air-backend-#222
=> Revert "Pagination default limit added"

config/ckeditor.js, types/generated/components.d.ts
=> HA:228-Ck editor dropdown fix

src/api/country/content-types/country/schema.json, src/api/country/controllers/country.ts, src/api/country/routes/country.ts, src/api/country/routes/custom-country.ts, src/api/country/services/country.ts, src/api/deal/content-types/deal/schema.json, src/api/destination/content-types/destination/schema.json, src/api/tour-location/content-types/tour-location/schema.json, src/api/tours-detail/content-types/tours-detail/schema.json, types/generated/components.d.ts, types/generated/contentTypes.d.ts
Reverts tmuller-ha/harbour-air-backend-#247
=> Revert "Destination Implementation"

config/ckeditor.js
=> Ck Editor Fix

types/generated/components.d.ts, types/generated/contentTypes.d.ts
=> Request a quote

src/api/parcel-express/content-types/parcel-express/schema.json, src/components/parcel-express/shipping-cost.json, types/generated/components.d.ts, types/generated/contentTypes.d.ts
=> Form Added

src/api/car-service/content-types/car-service/schema.json, types/generated/contentTypes.d.ts
=> Car Service Form

.github/workflows/dev-deploy.yml, config/plugins.ts, package.json, src/api/email-option/controllers/email-option.ts, yarn.lock
=> HA-666: Email Integration Sendgrid

.github/workflows/dev-deploy.yml
Reverts tmuller-ha/harbour-air-backend-#341
=> Revert "Label added for runner"

config/plugins.ts, package.json
Reverts tmuller-ha/harbour-air-backend-#375
=> Revert "Deployment plugin configuration added"
